# Generated by Django 5.1.5 on 2025-02-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
